### ISSUE TITLE
can't catch process:restart

### ISSUE THREAD

**Issue by linrf** [soyuka/pm2-notify#5]
Hello,
I am trying to catch process:restart.
But after testing the bus system, the only events I saw emitted were **stopping**,**stopped** & **online**. 

The config.example.yml says that the events list includes:
- restart
- delete
- stop
- restart overlimit
- exit
- start
- online

Is there any way I can achieve that?

**Comment by soyuka** [comment]
Hi, there are no such events, the only one we're listening to here is `process:event`.

Then, you have to check `event.event` which will be one of the above list. See here: 

https://github.com/soyuka/pm2-notify/blob/a7d30ed4579d56a9b7e6a5a24ced381f7647f1a8/index.js#L124

Be careful as in my script I skip every manual event (`event.manually`) which means that if the user does `pm2 restart foo.js` it'll not be interpreted.

I hope I answered correctly!

**Comment by linrf** [comment]
Thanks for your help!
